[book]
title = "Soroban Cookbook"
authors = ["Soroban Cookbook Contributors"]
description = "A comprehensive guide to building smart contracts on Stellar with Soroban"
language = "en"
src = "book/src"

[build]
build-dir = "book-output"

[output.html]
default-theme = "rust"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/Soroban-Cookbook/Soroban-Cookbook"
edit-url-template = "https://github.com/Soroban-Cookbook/Soroban-Cookbook/edit/main/{path}"

[output.html.search]
enable = true
